name: Deploy GitHub Pages with LFS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Remove Git metadata
        run: |
          git lfs uninstall
          rm -rf .git
          rm .gitattributes

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages